# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='dress_size',
            field=models.CharField(choices=[(b'Small', b'Small'), (b'Medium', b'Medium'), (b'Large', b'Large'), (b'X-Large', b'X-Large')], default=b'Medium', max_length=10),
        ),
    ]
